---
name: CI

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  typecheck:
    name: Typecheck
    runs-on: [self-hosted, x64]
    timeout-minutes: 10
    steps:
      - name: Typecheck
        run: |
          yarn typecheck

  test:
    name: Test
    runs-on: [self-hosted, x64]
    timeout-minutes: 10
    steps:
      - name: Test
        run: |
          yarn test:ci

  build:
    name: Build
    runs-on: [self-hosted, x64]
    timeout-minutes: 10
    steps:
      - name: Build
        run: |
          yarn build
